version: '3'

services:
      
  pgadmin-2:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "leshiota@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "110719"
    ports:
      - "8080:80"
    networks:
      - postgres-compose-network

  pg-database2:
    image: postgres:13
    environment:
    - POSTGRES_USER=root 
    - POSTGRES_PASSWORD=root 
    - POSTGRES_DB=ny_taxi 
    # volumes: 
    #   - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge